In [28]:
import numpy as np

import plotly.express as px
import plotly.io as pio
pio.templates.default = 'plotly_dark'

In [29]:
import tensorflow as tf

## NN из одного нейрона для умножения числа на 3

In [30]:
from keras.models import Sequential # sequense of layers in NN

from keras.layers import Dense # класс полносвязного/линейного слоя
from keras.layers import Input # класс входного слоя

from keras.utils import set_random_seed
set_random_seed(42)

In [31]:

# Создадим модель с одним слоем (он же будет выходным слоем),
model = Sequential([
    Input((1,)),
    Dense(
        1, # в котором будет всего один нейрон.
        activation='linear' # Используем линейную активацию
    )
])
model.summary()

w, b = model.get_weights()
print("Веса модели инициализированы случайными значениями:")
print(f"w = {w[0,0]}, b = {b[0]}")

Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_6 (Dense)                 │ (None, 1)              │             2 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2 (8.00 B)

 Trainable params: 2 (8.00 B)

 Non-trainable params: 0 (0.00 B)

Веса модели инициализированы случайными значениями:
w = 1.2408033609390259, b = 0.0


In [32]:
# "Скомпилируем" модель, то есть зададим:
model.compile(
    optimizer='sgd', # оптимизатор (стохастический град спуск),
    loss='mse',      # функцию потерь, которая будет минимизироваться,
    metrics=['mae']  # метрики
)

In [33]:
X_train = np.array([[1], [2], [3], [4], [5], [6], [7], [8], [9], [10]])
y_train = np.array([3, 6, 9, 12, 15, 18, 21, 24, 27, 30])

In [34]:
model.fit(X_train, y_train, epochs=100)

Epoch 1/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 144ms/step - loss: 119.1488 - mae: 9.6756
Epoch 2/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 5.4791 - mae: 2.0319
Epoch 3/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.2637 - mae: 0.4198
Epoch 4/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.0243 - mae: 0.1338
Epoch 5/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0132 - mae: 0.0988
Epoch 6/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0126 - mae: 0.0947
Epoch 7/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0125 - mae: 0.0936
Epoch 8/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0124 - mae: 0.0930
Epoch 9/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0123 - mae: 0.0926
Epoch 10/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0122 - mae: 0.0922
Epoch 11/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0121 - mae: 0.0918
Epoch 12/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0120 - mae: 0.0914
Epoch 13/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/

In [35]:
model.get_weights()

[array([[2.9766529]], dtype=float32), array([0.16253768], dtype=float32)]

In [36]:
model.predict(np.array([[-5], [33]]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step


array([[-14.720727],
       [ 98.39208 ]], dtype=float32)

## NN для сложения двух чисел

In [37]:
# Сгенерируем обучающие данные
X1 = np.random.randint(1, 10, size=100).reshape(-1,1)
X2 = np.random.randint(1, 10, size=100).reshape(-1,1)
X_train = np.hstack([X1, X2])
y_train = X1 + X2

Поскольку НС использует для оптимизации градиентный спуск входные данные нужно отмасштабировать:

In [38]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
X_scaled = scaler.fit_transform(X_train)

Создадим НС с двумя входыми и двумя слоями: скрытый слой и выходной слой

<img src="images/NN2.jpeg" width=500px>

In [39]:
model = Sequential([
    Input((2,)),
    Dense(3, activation='linear'),
    Dense(1, activation='linear')
])
model.summary()
model.get_weights()

Model: "sequential_6"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_7 (Dense)                 │ (None, 3)              │             9 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_8 (Dense)                 │ (None, 1)              │             4 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 13 (52.00 B)

 Trainable params: 13 (52.00 B)

 Non-trainable params: 0 (0.00 B)

[array([[ 1.049778  , -0.03939688,  0.58299136],
        [ 0.5321075 ,  0.69231975, -0.8354329 ]], dtype=float32),
 array([0., 0., 0.], dtype=float32),
 array([[ 0.83980453],
        [-0.05656397],
        [-0.28837383]], dtype=float32),
 array([0.], dtype=float32)]

In [40]:
model.compile(optimizer='sgd', loss='mse', metrics=['mape'])

model.fit(X_scaled, y_train, epochs=100)

Epoch 1/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 93.3622 - mape: 87.7178   
Epoch 2/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 28.5598 - mape: 40.7291 
Epoch 3/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2.9367 - mape: 19.8778 
Epoch 4/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2.0715 - mape: 19.7736 
Epoch 5/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.8725 - mape: 18.9612 
Epoch 6/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.6884 - mape: 18.0202 
Epoch 7/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.5187 - mape: 17.0977 
Epoch 8/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.3628 - mape: 16.2029 
Epoch 9/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.2200 - mape: 15.3361 
Epoch 10/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.0896 - mape: 14.4980 
Epoch 11/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.9708 - mape: 13.6891
Epoch 12/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.8629 - mape: 12.9096 
Epoch 13/100
4/4 ━━━━

In [41]:
model.predict(scaler.transform(np.array([[-10, 33]])))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step


array([[22.997866]], dtype=float32)

## NN для датасета *MNIST*

Картинки с рукописными цифрами 28 $\times$ 28 пикселей

In [42]:
from keras.datasets import mnist
(X_train, y_train), (X_test, y_test) = mnist.load_data()
X_train.shape, X_test.shape

((60000, 28, 28), (10000, 28, 28))

In [43]:
px.imshow(np.hstack(X_train[:5]), width=1000, height=300).update_coloraxes(showscale=False).show()
y_train[:5]

array([5, 0, 4, 1, 9], dtype=uint8)

Уменьшим размер картинок для сокращения количества признаков:

In [44]:
reduced_size = (14, 14)

X_train_resized = tf.image.resize(X_train[..., np.newaxis], reduced_size)[..., 0]
X_test_resized = tf.image.resize(X_test[..., np.newaxis], reduced_size)[..., 0]

px.imshow(np.hstack(X_train_resized[:5]), width=1000, height=300).update_coloraxes(showscale=False).show()

In [45]:
print(f"Диапазон значений пикселей: от {X_train.min()} до {X_train.max()}")

Диапазон значений пикселей: от 0 до 255


Нормируем данные простым делением на максимальное значение (255):

In [46]:
X_train_scaled = X_train_resized / 255
X_test_scaled = X_test_resized / 255

In [47]:
from keras.utils import to_categorical

y_train_cat = to_categorical(y_train)
y_train_cat.shape

(60000, 10)

In [48]:
from keras.layers import Flatten # класс входного слоя с переводом в одномерный массив

model = Sequential([
    Flatten(),
    Dense(10, activation='sigmoid')
])

model.compile(loss='categorical_crossentropy', optimizer='sgd', metrics=['accuracy'])

In [49]:
model.fit(X_train_scaled, y_train_cat, epochs=50)

Epoch 1/50
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 1s 459us/step - accuracy: 0.5690 - loss: 1.6724
Epoch 2/50
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 1s 525us/step - accuracy: 0.8364 - loss: 0.7977
Epoch 3/50
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 1s 427us/step - accuracy: 0.8603 - loss: 0.6276
Epoch 4/50
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 1s 438us/step - accuracy: 0.8704 - loss: 0.5516
Epoch 5/50
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 1s 423us/step - accuracy: 0.8762 - loss: 0.5071
Epoch 6/50
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 1s 420us/step - accuracy: 0.8807 - loss: 0.4772
Epoch 7/50
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 1s 440us/step - accuracy: 0.8837 - loss: 0.4555
Epoch 8/50
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 1s 442us/step - accuracy: 0.8859 - loss: 0.4390
Epoch 9/50
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 1s 453us/step - accuracy: 0.8877 - loss: 0.4257
Epoch 10/50
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 1s 437us/step - accuracy: 0.8896 - loss: 0.4149
Epoch 11/50
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 1s 422us/step - accuracy: 0.8910 - loss: 0.4059
Epoch 12

In [ ]:
y_test_pred = model.predict(X_test_scaled).argmax(axis=1)

from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_test_pred)

313/313 ━━━━━━━━━━━━━━━━━━━━ 0s 303us/step


0.9146