In [1]:
import numpy as np

import plotly.express as px
import plotly.io as pio
pio.templates.default = 'plotly_dark'

In [2]:
import tensorflow as tf

from keras.layers import Dense, Input
from keras.models import Sequential

## NN из одного нейрона для умножения числа на 3

In [3]:
from keras.models import Sequential # sequense of layers in NN

from keras.layers import Dense # класс полносвязного/линейного слоя
from keras.layers import Input # класс входного слоя

from keras.utils import set_random_seed
set_random_seed(42)

In [4]:

# Создадим модель с одним слоем (он же будет выходным слоем),
model = Sequential([
    Input((1,)),
    Dense(
        1, # в котором будет всего один нейрон.
        activation='linear' # Используем линейную активацию
    )
])
model.summary()

w, b = model.get_weights()
print("Веса модели инициализированы случайными значениями:")
print(f"w = {w[0,0]}, b = {b[0]}")

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 1)                   │               2 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 2 (8.00 B)

 Trainable params: 2 (8.00 B)

 Non-trainable params: 0 (0.00 B)

Веса модели инициализированы случайными значениями:
w = 1.2408033609390259, b = 0.0


In [5]:
# "Скомпилируем" модель, то есть зададим:
model.compile(
    optimizer='sgd', # оптимизатор (стохастический град спуск),
    loss='mse',      # функцию потерь, которая будет минимизироваться,
    metrics=['mae']  # метрики
)

In [8]:
X_train = np.array([[1], [2], [3], [4], [5], [6], [7], [8], [9], [10]])
y_train = np.array([3, 6, 9, 12, 15, 18, 21, 24, 27, 30])

In [9]:
model.fit(X_train, y_train, epochs=100)

Epoch 1/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 909ms/step - loss: 119.1488 - mae: 9.6756
Epoch 2/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 271ms/step - loss: 5.4791 - mae: 2.0319
Epoch 3/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - loss: 0.2637 - mae: 0.4198
Epoch 4/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - loss: 0.0243 - mae: 0.1338
Epoch 5/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - loss: 0.0132 - mae: 0.0988
Epoch 6/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - loss: 0.0126 - mae: 0.0947
Epoch 7/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 134ms/step - loss: 0.0125 - mae: 0.0936
Epoch 8/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - loss: 0.0124 - mae: 0.0930
Epoch 9/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 137ms/step - loss: 0.0123 - mae: 0.0926
Epoch 10/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 135ms/step - loss: 0.0122 - mae: 0.0922
Epoch 11/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 149ms/step - loss: 0.0121 - mae: 0.0918
Epoch 12/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 124ms/step - loss: 0.0120 - mae: 0.0914
Epoch 13/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s

In [10]:
model.get_weights()

[array([[2.9766529]], dtype=float32), array([0.16253768], dtype=float32)]

In [11]:
model.predict(np.array([[-5], [33]]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step


array([[-14.720727],
       [ 98.39208 ]], dtype=float32)

## NN для сложения двух чисел

In [13]:
# Сгенерируем обучающие данные
X1 = np.random.randint(1, 10, size=100).reshape(-1,1)
X2 = np.random.randint(1, 10, size=100).reshape(-1,1)
X_train = np.hstack([X1, X2])
y_train = X1 + X2

Поскольку НС использует для оптимизации градиентный спуск входные данные нужно отмасштабировать:

In [14]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
X_scaled = scaler.fit_transform(X_train)

Создадим НС с двумя входыми и двумя слоями: скрытый слой и выходной слой

<img src="https://github.com/sidorov-works/nn-basics/blob/main/images/NN2.jpeg?raw=1" width=500px>

In [24]:
# initializer = 'glotot_uniform'
initializer = 'zeros'

model = Sequential([
    Input((2,)),
    Dense(3, activation='linear', kernel_initializer=initializer),
    Dense(1, activation='linear', kernel_initializer=initializer)
])
model.summary()
model.get_weights()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_7 (Dense)                      │ (None, 3)                   │               9 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_8 (Dense)                      │ (None, 1)                   │               4 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 13 (52.00 B)

 Trainable params: 13 (52.00 B)

 Non-trainable params: 0 (0.00 B)

[array([[0., 0., 0.],
        [0., 0., 0.]], dtype=float32),
 array([0., 0., 0.], dtype=float32),
 array([[0.],
        [0.],
        [0.]], dtype=float32),
 array([0.], dtype=float32)]

In [25]:
model.compile(optimizer='sgd', loss='mse', metrics=['mape'])

model.fit(X_scaled, y_train, epochs=100)

Epoch 1/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 54ms/step - loss: 98.0678 - mape: 98.3261
Epoch 2/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 84.3783 - mape: 87.4654  
Epoch 3/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 72.8299 - mape: 77.4478 
Epoch 4/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 63.0953 - mape: 69.3979 
Epoch 5/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 54.8969 - mape: 63.7458 
Epoch 6/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 47.9989 - mape: 59.1293 
Epoch 7/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 42.2013 - mape: 55.1310 
Epoch 8/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 37.3343 - mape: 52.4933 
Epoch 9/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 33.2541 - mape: 50.1803 
Epoch 10/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 29.8384 - mape: 48.4623 
Epoch 11/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 26.9839 - mape: 47.0069 
Epoch 12/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 24.6027 - mape: 45.7938 
Epoch 13/100

In [26]:
model.predict(scaler.transform(np.array([[-10, 33]])))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step


array([[10.188717]], dtype=float32)

## NN для датасета *MNIST*

Картинки с рукописными цифрами 28 $\times$ 28 пикселей

In [ ]:
from keras.datasets import mnist
(X_train, y_train), (X_test, y_test) = mnist.load_data()
X_train.shape, X_test.shape

((60000, 28, 28), (10000, 28, 28))

In [ ]:
px.imshow(np.hstack(X_train[:5]), width=1000, height=300).update_coloraxes(showscale=False).show()
y_train[:5]

array([5, 0, 4, 1, 9], dtype=uint8)

Уменьшим размер картинок для сокращения количества признаков:

In [ ]:
reduced_size = (14, 14)

X_train_resized = tf.image.resize(X_train[..., np.newaxis], reduced_size)[..., 0]
X_test_resized = tf.image.resize(X_test[..., np.newaxis], reduced_size)[..., 0]

px.imshow(np.hstack(X_train_resized[:5]), width=1000, height=300).update_coloraxes(showscale=False).show()

In [ ]:
print(f"Диапазон значений пикселей: от {X_train.min()} до {X_train.max()}")

Диапазон значений пикселей: от 0 до 255


Нормируем данные простым делением на максимальное значение (255):

In [ ]:
X_train_scaled = X_train_resized / 255
X_test_scaled = X_test_resized / 255

In [ ]:
from keras.utils import to_categorical

y_train_cat = to_categorical(y_train)
y_train_cat.shape

(60000, 10)

In [ ]:
from keras.layers import Flatten # класс входного слоя с переводом в одномерный массив

model = Sequential([
    Flatten(),
    Dense(10, activation='sigmoid')
])

model.compile(loss='categorical_crossentropy', optimizer='sgd', metrics=['accuracy'])

In [ ]:
model.fit(X_train_scaled, y_train_cat, epochs=50)

Epoch 1/50
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 1s 425us/step - accuracy: 0.5551 - loss: 1.6840
Epoch 2/50
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 1s 441us/step - accuracy: 0.8381 - loss: 0.7975
Epoch 3/50
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 1s 440us/step - accuracy: 0.8608 - loss: 0.6269
Epoch 4/50
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 1s 442us/step - accuracy: 0.8699 - loss: 0.5509
Epoch 5/50
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 1s 446us/step - accuracy: 0.8764 - loss: 0.5064
Epoch 6/50
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 1s 425us/step - accuracy: 0.8809 - loss: 0.4766
Epoch 7/50
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 1s 403us/step - accuracy: 0.8843 - loss: 0.4550
Epoch 8/50
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 1s 395us/step - accuracy: 0.8865 - loss: 0.4384
Epoch 9/50
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 1s 409us/step - accuracy: 0.8886 - loss: 0.4253
Epoch 10/50
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 1s 404us/step - accuracy: 0.8902 - loss: 0.4145
Epoch 11/50
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 1s 397us/step - accuracy: 0.8920 - loss: 0.4054
Epoch 12

In [ ]:
y_test_pred = model.predict(X_test_scaled).argmax(axis=1)

from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_test_pred)

313/313 ━━━━━━━━━━━━━━━━━━━━ 0s 287us/step


0.9149